    Organizations:
        - &OrdererOrg
            Name: OrdererMSP
            ID: OrdererMSP
            MSPDir: crypto-config/ordererOrganizations/orderermanagement.com/msp
            Policies:
                Readers:
                    Type: Signature
                    Rule: "OR('OrdererMSP.member')"
                Writers:
                    Type: Signature
                    Rule: "OR('OrdererMSP.member')"
                Admins:
                    Type: Signature
                    Rule: "OR('OrdererMSP.admin')"
        - &Org1
            Name: AudiMSP
            ID: AudiMSP
            MSPDir: crypto-config/peerOrganizations/audi.orderermanagement.com/msp
            Policies:
                Readers:
                    Type: Signature
                    Rule: "OR('AudiMSP.admin', 'AudiMSP.peer', 'AudiMSP.client')"
                Writers:
                    Type: Signature
                    Rule: "OR('AudiMSP.admin', 'AudiMSP.client')"
                Admins:
                    Type: Signature
                    Rule: "OR('AudiMSP.admin')"
            AnchorPeers:
                - Host: peer0.audi.orderermanagement.com
                  Port: 7051
        - &Org2
            Name: BridgestoneMSP
            ID: BridgestoneMSP
            MSPDir: crypto-config/peerOrganizations/bridgestone.orderermanagement.com/msp
            Policies:
                Readers:
                    Type: Signature
                    Rule: "OR('BridgestoneMSP.admin', 'BridgestoneMSP.peer', 'BridgestoneMSP.client')"
                Writers:
                    Type: Signature
                    Rule: "OR('BridgestoneMSP.admin', 'BridgestoneMSP.client')"
                Admins:
                    Type: Signature
                    Rule: "OR('BridgestoneMSP.admin')"
            AnchorPeers:
                - Host: peer0.bridgestone.orderermanagement.com
                  Port: 9051
        - &Org3
            Name: MrfMSP
            ID: MrfMSP
            MSPDir: crypto-config/peerOrganizations/mrf.orderermanagement.com/msp
            Policies:
                Readers:
                    Type: Signature
                    Rule: "OR('MrfMSP.admin', 'MrfMSP.peer', 'MrfMSP.client')"
                Writers:
                    Type: Signature
                    Rule: "OR('MrfMSP.admin', 'MrfMSP.client')"
                Admins:
                    Type: Signature
                    Rule: "OR('MrfMSP.admin')"
            AnchorPeers:
                - Host: peer0.mrf.orderermanagement.com
                  Port: 11051
    Capabilities:
        Channel: &ChannelCapabilities
            V1_3: true
        Orderer: &OrdererCapabilities
            V1_1: true
        Application: &ApplicationCapabilities
            V1_3: true
            V1_2: false
            V1_1: false
    Application: &ApplicationDefaults
        Organizations:
        Policies:
            Readers:
                Type: ImplicitMeta
                Rule: "ANY Readers"
            Writers:
                Type: ImplicitMeta
                Rule: "ANY Writers"
            Admins:
                Type: ImplicitMeta
                Rule: "MAJORITY Admins"
        Capabilities:
            <<: *ApplicationCapabilities
    Orderer: &OrdererDefaults
        OrdererType: solo
        Addresses:
            - orderer.orderermanagement.com:7050
        BatchTimeout: 2s
        BatchSize:
            MaxMessageCount: 10
            AbsoluteMaxBytes: 99 MB
            PreferredMaxBytes: 512 KB
        Organizations:
        Policies:
            Readers:
                Type: ImplicitMeta
                Rule: "ANY Readers"
            Writers:
                Type: ImplicitMeta
                Rule: "ANY Writers"
            Admins:
                Type: ImplicitMeta
                Rule: "MAJORITY Admins"
            BlockValidation:
                Type: ImplicitMeta
                Rule: "ANY Writers"
    Channel: &ChannelDefaults
        Policies:
            Readers:
                Type: ImplicitMeta
                Rule: "ANY Readers"
            Writers:
                Type: ImplicitMeta
                Rule: "ANY Writers"
            Admins:
                Type: ImplicitMeta
                Rule: "MAJORITY Admins"
        Capabilities:
            <<: *ChannelCapabilities
    Profiles:
        OrdererManagementGenesis:
            <<: *ChannelDefaults
            Orderer:
                <<: *OrdererDefaults
                Organizations:
                    - *OrdererOrg
                Capabilities:
                    <<: *OrdererCapabilities
            Consortiums:
                SampleConsortium:
                    Organizations:
                        - *Org1
                        - *Org2
                        - *Org3
        AB_Channel:
            Consortium: SampleConsortium
            <<: *ChannelDefaults
            Application:
                <<: *ApplicationDefaults
                Organizations:
                    - *Org1
                    - *Org2
                Capabilities:
                    <<: *ApplicationCapabilities
        AM_Channel:
            Consortium: SampleConsortium
            <<: *ChannelDefaults
            Application:
                <<: *ApplicationDefaults
                Organizations:
                    - *Org1
                    - *Org3
                Capabilities:
                    <<: *ApplicationCapabilities