version: '2'

services:

  orderer.orderermanagement.com:
    container_name: orderer.orderermanagement.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/orderermanagement.com/orderers/orderer.orderermanagement.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/orderermanagement.com/orderers/orderer.orderermanagement.com/tls/:/var/hyperledger/orderer/tls
        - orderer.orderermanagement.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.audi.orderermanagement.com:
    container_name: peer0.audi.orderermanagement.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.audi.orderermanagement.com
      - CORE_PEER_ADDRESS=peer0.audi.orderermanagement.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.audi.orderermanagement.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.audi.orderermanagement.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.audi.orderermanagement.com:7051
      - CORE_PEER_LOCALMSPID=AudiMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/audi.orderermanagement.com/peers/peer0.audi.orderermanagement.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/audi.orderermanagement.com/peers/peer0.audi.orderermanagement.com/tls:/etc/hyperledger/fabric/tls
        - peer0.audi.orderermanagement.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer1.audi.orderermanagement.com:
    container_name: peer1.audi.orderermanagement.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.audi.orderermanagement.com
      - CORE_PEER_ADDRESS=peer1.audi.orderermanagement.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.audi.orderermanagement.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.audi.orderermanagement.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.audi.orderermanagement.com:7051
      - CORE_PEER_LOCALMSPID=AudiMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/audi.orderermanagement.com/peers/peer1.audi.orderermanagement.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/audi.orderermanagement.com/peers/peer1.audi.orderermanagement.com/tls:/etc/hyperledger/fabric/tls
        - peer1.audi.orderermanagement.com:/var/hyperledger/production
    ports:
      - 8051:8051

  peer0.bridgestone.orderermanagement.com:
    container_name: peer0.bridgestone.orderermanagement.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.bridgestone.orderermanagement.com
      - CORE_PEER_ADDRESS=peer0.bridgestone.orderermanagement.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.bridgestone.orderermanagement.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.bridgestone.orderermanagement.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.bridgestone.orderermanagement.com:10051
      - CORE_PEER_LOCALMSPID=BridgestoneMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/bridgestone.orderermanagement.com/peers/peer0.bridgestone.orderermanagement.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/bridgestone.orderermanagement.com/peers/peer0.bridgestone.orderermanagement.com/tls:/etc/hyperledger/fabric/tls
        - peer0.bridgestone.orderermanagement.com:/var/hyperledger/production
    ports:
      - 9051:9051

  peer1.bridgestone.orderermanagement.com:
    container_name: peer1.bridgestone.orderermanagement.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.bridgestone.orderermanagement.com
      - CORE_PEER_ADDRESS=peer1.bridgestone.orderermanagement.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.bridgestone.orderermanagement.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.bridgestone.orderermanagement.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.bridgestone.orderermanagement.com:9051
      - CORE_PEER_LOCALMSPID=BridgestoneMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/bridgestone.orderermanagement.com/peers/peer1.bridgestone.orderermanagement.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/bridgestone.orderermanagement.com/peers/peer1.bridgestone.orderermanagement.com/tls:/etc/hyperledger/fabric/tls
        - peer1.bridgestone.orderermanagement.com:/var/hyperledger/production
    ports:
      - 10051:10051

  peer0.mrf.orderermanagement.com:
    container_name: peer0.mrf.orderermanagement.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.mrf.orderermanagement.com
      - CORE_PEER_ADDRESS=peer0.mrf.orderermanagement.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.mrf.orderermanagement.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.mrf.orderermanagement.com:11051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.mrf.orderermanagement.com:12051
      - CORE_PEER_LOCALMSPID=MrfMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/mrf.orderermanagement.com/peers/peer0.mrf.orderermanagement.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/mrf.orderermanagement.com/peers/peer0.mrf.orderermanagement.com/tls:/etc/hyperledger/fabric/tls
        - peer0.mrf.orderermanagement.com:/var/hyperledger/production
    ports:
      - 11051:11051

  peer1.mrf.orderermanagement.com:
    container_name: peer1.mrf.orderermanagement.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.mrf.orderermanagement.com
      - CORE_PEER_ADDRESS=peer1.mrf.orderermanagement.com:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer1.mrf.orderermanagement.com:12052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.mrf.orderermanagement.com:12051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.mrf.orderermanagement.com:11051
      - CORE_PEER_LOCALMSPID=MrfMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/mrf.orderermanagement.com/peers/peer1.mrf.orderermanagement.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/mrf.orderermanagement.com/peers/peer1.mrf.orderermanagement.com/tls:/etc/hyperledger/fabric/tls
        - peer1.mrf.orderermanagement.com:/var/hyperledger/production
    ports:
      - 12051:12051